server:
  port: 6001

eureka:
  ##instance:
   ## hostname: order-service-6001
   ## instance-id: order-service-6001
    ##prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

spring:
  application:
    name: cloud-consumer-service